import{a as d,S as h,i as y}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(r){if(r.ep)return;r.ep=!0;const a=n(r);fetch(r.href,a)}})();const t={page:1,per_page:40,totalHits:0,receivedHits:0,totalPages:0,searchQuery:null,isLoading:!1},l={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};d.defaults.headers.common["x-api-key"]="live_nOdnL3Dj9jjF4zVLjteozldoqmiVUxxCRsrlPoRVyonLQDm4DFuaUNiaRzafsnXC";d.defaults.headers=["Access-Control-Allow-Origin"];async function p(e){const o=new URLSearchParams({key:"44202133-14fac6110a8eccaaec992feaf",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:t.per_page,page:t.page}),s=await(await d.get(`https://pixabay.com/api/?${o.toString()}`)).data;return console.log(`data:
`,s),s}const u=new h(".gallery a",{captionsData:"alt",captionDelay:250});u.on("error.simplelightbox",function(e){console.log(e)});l.form.addEventListener("submit",v);window.addEventListener("scroll",L);function L(){window.scrollY+window.innerHeight>=document.documentElement.scrollHeight-50&&w()}async function v(e){e.preventDefault(),l.gallery.textContent="";const o=e.target.elements.searchQuery.value;if(t.searchQuery=o,!o){i("Please enter a search query.","error");return}t.receivedHits=0,t.totalHits=0,t.page=1;try{await f(),t.totalHits??i(`Hooray! We found ${t.totalHits} images.`,"success"),u.refresh()}catch{i("Sorry, there are no images matching your search query. Please try again.","error")}finally{e.target.elements.searchQuery.value=""}}async function f(){if(l.loader.classList.remove("hide"),!t.isLoading){t.isLoading=!0;try{const{totalHits:e,hits:o}=await p(t.searchQuery);t.receivedHits+=o.length,t.totalHits=e,b(o),u.refresh(),console.log("hits received: ",t.receivedHits),console.log("total hits: ",e),t.receivedHits?t.receivedHits>=e&&i("We're sorry, but you've reached the end of search results.","info"):i("Sorry, there are no images matching your search query. Please try again.","error")}catch{i("Error fetching data. Please try again.","error")}finally{l.loader.classList.add("hide"),t.isLoading=!1}}}async function w(){t.page+=1,await f();const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function b(e){const o=e.map(({largeImageURL:n,webformatURL:s,tags:r,likes:a,views:c,comments:g,downloads:m})=>`
      <div class="photo-card">
        <a href="${n}" class="card-link">
          <img src="${s}" alt="${r}" class="card-image" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${a}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${g}</p>
          <p class="info-item"><b>Downloads</b> ${m}</p>
        </div>
      </div>
    `).join("");l.gallery.insertAdjacentHTML("beforeend",o)}function i(e,o="info"){y[o]({message:e,position:"topRight",timeout:3e3})}
//# sourceMappingURL=commonHelpers.js.map
